### ISSUE TITLE
Check "No iotas found for payout" bug 

### ISSUE THREAD

**Issue by huhn511** [iota-pay/iota-payment-module#19]
Devnet faucet logs "No iotas found for payout" while balance method returns a non zero value. 

Please check this behavior. 

https://faucet.einfachiota.de/#/

![Bildschirmfoto 2020-03-09 um 13 29 23](https://user-images.githubusercontent.com/10562055/76214156-73ca7880-620c-11ea-93a3-ba3f5938ef41.png)

**Comment by Thoralf-M** [comment]
Probably caused by the node errors
<https://github.com/iota-pay/iota-payment-module/blob/ad63d38ae51243b7bbb51560b0e8230d71a02938/lib/payout.js#L231>
needs to be updated after the transaction was sent (and the trytes should be stored before)
