### ISSUE TITLE
devnet(comnet?) settings as default, have the option to change everything in the .env

### ISSUE THREAD

**Issue by Thoralf-M** [iota-pay/iota-payment-module#20]

**Comment by huhn511** [comment]
I thinking about hiding the "devnet" and "livenet" settings, like nodes and MWM, from the user.

So we could provide a default variable: "livenet:true" or something, devnet is default. 
Wave a list off different nodes and if the user want, he also can add a custom node to the settings. 

In this case, the user doesn't need to know anything about nodes and its fully customizable. 

What do you think?

**Comment by Thoralf-M** [comment]
I thought about using the nodeInfo to detect the devnet and apply the settings. If the node is in the devnet the feature is `testnet`, but if someone wants another private testnet with an even lower MWM it wouldn't work anymore
I think the IOTA nodes should have a better API 😄

**Comment by huhn511** [comment]
So - you also can apply your MVM to the options. We just have to set good defaults.

With no configuration -> ready for devnet

**Comment by Thoralf-M** [comment]
Sounds good

**Comment by Thoralf-M** [comment]
`network=mainnet` should be enough to use the module in the mainnet

**Comment by Thoralf-M** [comment]
https://github.com/iota-pay/iota-payment-module/commit/c2d6aa39ac9a43895615300ca7f1cc6096a8383a
