### ISSUE TITLE
test if "build:dashboard" is not needed anymore 

### ISSUE THREAD

**Issue by huhn511** [iota-pay/iota-payment-module#9]
if yes, remove docs in https://github.com/einfachiota/iota-payment/blob/5f17d4768fa5ee28026c389ab064fdad5160479e/examples/02_express_server_with_gui%2Bapi.js#L10

**Comment by huhn511** [comment]
The dashboard is not loading anymore. Also after building it in the node modules directory. 

- [ ] Find the problem
- [ ] Find a solution

**Comment by Thoralf-M** [comment]
`app.use('/iotapay', express.static(__dirname +'/../dashboard/dist'))`
should fix it, because it takes the path from where it's called I think

**Comment by Thoralf-M** [comment]
https://github.com/iota-pay/iota-payment-module/commit/08a6b7994b3c9438cfb6b9554ea8ece75ac54224
